version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: onlinejudge-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: onlinejudge
    volumes:
      - /mnt/c/OnlineJudge/db-init:/docker-entrypoint-initdb.d
    networks:
      - onlinejudge-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onlinejudge-backend
    restart: always
    ports:
      - "5024:5024"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=onlinejudge;user=root;password=123123;
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
    
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - onlinejudge-network

  onlinejudge:
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - /mnt/c/OnlineJudge:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  onlinejudge-network:
    driver: bridge
